### ISSUE TITLE
Walletd: reset command not restarted from 0

### ISSUE THREAD

**Issue by mounirrquiba** [bbscoin/bbscoin#1]
Hello Team,

I need to restart sync but the only way is with reset, this command don't start from block 0,
Balance amount is wrong at all times, please can you help me,

Telegram account?

**Comment by randing89** [comment]
reset command restart sync from locally cached block data. In your case, the data was somehow corrupted. Remove the folder at ~/.BBSCoin or %appdata%/BBSCoin

Telegram channel is at https://t.me/bbscoin

**Comment by mounirrquiba** [comment]
Thanks!
