### ISSUE TITLE
Anyway to export keys or backup

### ISSUE THREAD

**Issue by KhmerRun** [bbscoin/bbscoin#3]
Hello,

Is there anyway to backup keys of wallet? I saw only these in help:

 address              Show current wallet public address
  balance              Show current wallet balance
  bc_height            Show blockchain height
  exit                 Close wallet
  help                 Show this help
  incoming_transfers   Show incoming transfers
  list_transfers       Show all known transfers
  payments             payments <payment_id_1> [<payment_id_2> ... <payment_id_N>] - Show payments <payment_id_1>, ... <payment_id_N>
  reset                Discard cache data and start synchronizing from the start
  save                 Save wallet synchronized data
  set_log              set_log <level> - Change current log level, <level> is a number 0-4
  start_mining         start_mining [<number_of_threads>] - Start mining in daemon
  stop_mining          Stop mining in daemon
  transfer             transfer <mixin_count> <addr_1> <amount_1> [<addr_2> <amount_2> ... <addr_N> <amount_N>] [-p payment_id] [-f fee] - Transfer <amount_1>,... <amount_N> to <address_1>,... <address_N>, respectively. <mixin_count> is the number of transactions yours is indistinguishable from (from 0 to maximum available)

**Comment by randing89** [comment]
you can just make a copy of the wallet file. there is no way to export the key at the moment
