### ISSUE TITLE
What will happen to pending transactions too large?

### ISSUE THREAD

**Issue by MoonGem** [bbscoin/bbscoin#7]
What will happen to pending transactions too large for a block?

**Comment by hatoyakohane** [comment]
The base max size of tranaction without miner fee is 100,000, if your transaction far beyond this size, your transaction may can't accept by miners. You should lower your anonymity level.

**Comment by MoonGem** [comment]
The anonymity level is 0, my transaction was cancelled then magically re-appeared back on the blockchain. What the fuck.

**Comment by MoonGem** [comment]
Yeah fuck this.
